name: Mirror from Gitee to GitHub

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone from Gitee
        env:
          GITEE_REPO_URL: ${{ secrets.GITEE_REPO_URL }}
        run: |
          git clone --mirror "$GITEE_REPO_URL" mirror

      - name: Push to GitHub
        run: |
          cd mirror
          git remote set-url --push origin https://x-access-token:${{ secrets.GIT_TOKEN_PUSH }}@github.com/${{ github.repository }}.git
          git push --mirror      
