name: Mirror from Gitee to GitHub

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout empty repo
        run: |
          git clone --mirror "$GITEE_REPO_URL" mirror
          cd mirror
          git remote set-url --push origin https://github.com/${{ github.repository }}.git
          git push --mirror

    env:
      GITEE_REPO_URL: ${{ secrets.GITEE_REPO_URL }}
      GIT_ASKPASS: /dev/null
      GIT_TERMINAL_PROMPT: 0
